### ISSUE TITLE
Prepare guidance for facilitators

### ISSUE THREAD

**Issue by danfowler** [okfn/data-tables.csv#13]
Guidance should be provided to facilitators for what is expected of them for their sessions.  This will obviously be quite loose so that facilitators can decide for themselves how to best run a session.

- [x] Length of session
- [ ] Guidance on how to run a successful session
  - [ ] Expectations for session attendees (e.g. bring laptop)
  - [ ] Start with a motivating example
  - [ ] Have some datasets prepped, etc.
  - [ ] Have advanced exercises
- [ ] What the facilitator should expect at their table (e.g. a monitor)

Some inspiration: 

- [Micheleen Harris: Tips I've Learned by Being a Trainer for a Year](https://michhar.github.io/posts/teaching-notes-post)
- [Michael Levy: Teaching R to 200 students in a week](http://environmentalpolicy.ucdavis.edu/node/394)

**Comment by pwalsh** [comment]
csv,conf,v3 is over!
